/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ded26ac8-6595-42d2-ade0-e5c2c28370e5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aB9dJIS4V",
    "aws_user_pools_web_client_id": "jv57au63h32m5kvke98dfrp4l",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api0bdbc7ee",
            "endpoint": "https://hbqbwyhppj.execute-api.us-east-1.amazonaws.com/devel",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
